Repository opensourcepos/opensourcepos, pull requests merged in 2019-02, with the labels that each got.

#2357 Cash rounding for Chile requires rounding to the nearest 10 pesos.
  application/views/configs/locale_config.php
Labels: bug

#2344 This fixes the improper display of the tax group
  application/libraries/Tax_lib.php
  application/models/Sale.php
  application/views/sales/invoice.php
  application/views/sales/invoice_email.php
  application/views/sales/quote.php
  application/views/sales/quote_email.php
  application/views/sales/receipt_default.php
  application/views/sales/receipt_email.php
  application/views/sales/receipt_short.php
  application/views/sales/register.php
  application/views/sales/tax_invoice.php
  application/views/sales/work_order.php
Labels: bug

#2322 fixed timezone (#2321)
  application/helpers/locale_helper.php
Labels: bug

#2343 Fixes a couple of problems with sales tax migration.
  application/controllers/Suppliers.php
  application/migrations/20190129212600_indiagst.php
  application/migrations/20190213210000_indiagst1.php
  application/migrations/20190220210000_indiagst2.php
  application/migrations/sqlscripts/3.2.1_to_3.3.0.sql
  application/migrations/sqlscripts/3.3.0_indiagst.sql
  application/migrations/sqlscripts/3.3.0_indiagst1.sql
  application/migrations/sqlscripts/3.3.0_indiagst2.sql
  application/models/reports/Summary_sales_taxes.php
  application/models/reports/Summary_taxes.php
Labels: bug

#2362 Add attribute type conversion, error checking.
  application/helpers/locale_helper.php
  application/models/Attribute.php
  application/views/attributes/form.php
Labels: bug, enhancement

#2364 System & Installation Info
  application/language/ar-EG/config_lang.php
  application/language/az-AZ/config_lang.php
  application/language/bg/config_lang.php
  application/language/cs/config_lang.php
  application/language/de-CH/config_lang.php
  application/language/de/config_lang.php
  application/language/el/config_lang.php
  application/language/en-GB/config_lang.php
  application/language/en-US/config_lang.php
  application/language/es/config_lang.php
  application/language/es_MX/config_lang.php
  application/language/fr/config_lang.php
  application/language/hr-HR/config_lang.php
  application/language/hu-HU/config_lang.php
  application/language/id/config_lang.php
  application/language/it/config_lang.php
  application/language/km/config_lang.php
  application/language/lo/config_lang.php
  application/language/ml/config_lang.php
  application/language/nl-BE/config_lang.php
  application/language/nl/config_lang.php
  application/language/pl/config_lang.php
  application/language/pt-BR/config_lang.php
  application/language/ro/config_lang.php
  application/language/ru/config_lang.php
  application/language/sv/config_lang.php
  application/language/th/config_lang.php
  application/language/tr/config_lang.php
  application/language/vi/config_lang.php
  application/language/zh-Hans/config_lang.php
  application/language/zh-Hant/config_lang.php
  application/views/configs/manage.php
  application/views/configs/system_info.php
  public/system_info.php
Labels: enhancement
