Repository opensourcepos/opensourcepos, pull requests merged in 2020-05, with the labels that each got.

#2814 Added ORDER BY to sort various dropdowns
  application/models/Attribute.php
  application/views/attributes/form.php
Labels: enhancement

#2792 Removing LEFT JOIN of supplier table
  application/models/Item.php
Labels: bug

#2805 Updating System Info Section
  application/language/ar-EG/config_lang.php
  application/language/ar-LB/config_lang.php
  application/language/az-AZ/config_lang.php
  application/language/bg/config_lang.php
  application/language/cs/config_lang.php
  application/language/da/config_lang.php
  application/language/de-CH/config_lang.php
  application/language/de/config_lang.php
  application/language/el/config_lang.php
  application/language/en-GB/config_lang.php
  application/language/en-US/config_lang.php
  application/language/es/config_lang.php
  application/language/es_MX/config_lang.php
  application/language/fr/config_lang.php
  application/language/he/config_lang.php
  application/language/hr-HR/config_lang.php
  application/language/hu-HU/config_lang.php
  application/language/id/config_lang.php
  application/language/it/config_lang.php
  application/language/km/config_lang.php
  application/language/lo/config_lang.php
  application/language/ml/config_lang.php
  application/language/nl-BE/config_lang.php
  application/language/nl/config_lang.php
  application/language/pl/config_lang.php
  application/language/pt-BR/config_lang.php
  application/language/ro/config_lang.php
  application/language/ru/config_lang.php
  application/language/sv/config_lang.php
  application/language/th/config_lang.php
  application/language/tl-PH/config_lang.php
  application/language/tr/config_lang.php
  application/language/ur_PK/config_lang.php
  application/language/vi/config_lang.php
  application/language/zh-Hans/config_lang.php
  application/language/zh-Hant/config_lang.php
  application/views/configs/manage.php
  application/views/configs/system_config.php
  application/views/configs/system_info.php
Labels: bug, enhancement

#2824 Custom image upload restrictions
  application/controllers/Config.php
  application/controllers/Items.php
  application/language/en-GB/config_lang.php
  application/language/en-US/config_lang.php
  application/migrations/20200508000000_image_upload_defaults.php
  application/views/configs/general_config.php
  application/views/items/form.php
Labels: bug, enhancement

#2816 Category as dropdown
  README.md
  application/controllers/Config.php
  application/controllers/Items.php
  application/language/ar-EG/config_lang.php
  application/language/ar-LB/config_lang.php
  application/language/az-AZ/config_lang.php
  application/language/bg/config_lang.php
  application/language/cs/config_lang.php
  application/language/da/config_lang.php
  application/language/de-CH/config_lang.php
  application/language/de/config_lang.php
  application/language/el/config_lang.php
  application/language/en-GB/config_lang.php
  application/language/en-US/config_lang.php
  application/language/es/config_lang.php
  application/language/es_MX/config_lang.php
  application/language/fr/config_lang.php
  application/language/he/config_lang.php
  application/language/hr-HR/config_lang.php
  application/language/hu-HU/config_lang.php
  application/language/id/config_lang.php
  application/language/id/sales_lang.php
  application/language/id/taxes_lang.php
  application/language/it/config_lang.php
  application/language/km/config_lang.php
  application/language/lo/config_lang.php
  application/language/ml/config_lang.php
  application/language/nl-BE/config_lang.php
  application/language/nl/config_lang.php
  application/language/pl/config_lang.php
  application/language/pt-BR/config_lang.php
  application/language/ro/config_lang.php
  application/language/ru/config_lang.php
  application/language/sv/config_lang.php
  application/language/th/attributes_lang.php
  application/language/th/bootstrap_tables_lang.php
  application/language/th/cashups_lang.php
  application/language/th/common_lang.php
  application/language/th/config_lang.php
  application/language/th/giftcards_lang.php
  application/language/th/items_lang.php
  application/language/th/suppliers_lang.php
  application/language/tl-PH/config_lang.php
  application/language/tr/attributes_lang.php
  application/language/tr/config_lang.php
  application/language/ur_PK/config_lang.php
  application/language/vi/config_lang.php
  application/language/zh-Hans/config_lang.php
  application/language/zh-Hant/config_lang.php
  application/libraries/Token_lib.php
  application/migrations/20200508000000_image_upload_defaults.php
  application/models/Item.php
  application/views/configs/general_config.php
  application/views/configs/manage.php
  application/views/configs/system_config.php
  application/views/configs/system_info.php
  application/views/items/form.php
Labels: enhancement
